### ISSUE TITLE
Health check query results are never retrieved

### ISSUE THREAD

**Issue by rschlussel** [prestodb/benchto#51] opened 2017-07-14 21:01 UTC
Benchto executes healthcheck queries between executions, but never retrieves the results. 

This causes the queries to hang in Presto with 100% progress until they time out with
```
com.facebook.presto.spi.PrestoException: Query 20170714_200842_00168_kz7bj has not been accessed since 2017-07-14T16:08:42.616-04:00: currentTime 2017-07-14T16:13:42.917-04:00
    at com.facebook.presto.execution.SqlQueryManager.failAbandonedQueries(SqlQueryManager.java:584)
    at com.facebook.presto.execution.SqlQueryManager$1.run(SqlQueryManager.java:180)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

The queries being executed are like the one below:
```
select nodes_count,
case nodes_count
when 9 then 1
else 1/0
end
from (
select count(*) nodes_count from system.runtime.nodes where state = 'active'
)
```

**Comment by szymonm** [comment] 2017-08-09 14:05
I'm investigating this.

**Comment by szymonm** [comment] 2017-08-10 13:27
@cawallin Do you have any thoughts on how to reproduce it?

**Comment by cawallin** [comment] 2017-08-10 13:55
Usually when running benchmarks either from Jenkins or locally it shows up.

**Comment by szymonm** [comment] 2017-08-17 13:33
Run simple benchmarks with #54 a couple of hundred times and can't reproduce the issue. Closing for now.

**Closed by szymonm** 2017-08-17 13:33 UTC

**Comment by SwapnaRavi21** [comment] 2019-11-11 16:41
hi,
Any update on this?
I have similar issue com.facebook.presto.spi.PrestoException: Query 20191111_162609_00141_vrkhx has not been accessed since 2019-11-11T16:32:05.517Z: currentTime 2019-11-11T16:37:06.260Z


Thanks

**Comment by jiechenghan** [comment] 2019-11-13 17:02
Hi
I also had the same problem.

The presto server version: 0.228
The presto cli version: 0.228
The query is a left outer join on two tables, one has 0.2 billion records and the one has 100,000 records.

After executing the query from presto cli, some result showed quick, then it's just freeze on the screen. In the meantime, the UI showed the query had a "User_ERROR" after 5minutes, with the error message as below:

com.facebook.presto.spi.PrestoException: Query 20191113_164748_00017_gztxj has not been accessed since 2019-11-13T10:47:50.224-06:00: currentTime 2019-11-13T10:52:51.218-06:00
	at com.facebook.presto.execution.QueryTracker.failAbandonedQueries(QueryTracker.java:323)
	at com.facebook.presto.execution.QueryTracker.lambda$start$0(QueryTracker.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by odellso** [comment] 2020-02-29 16:33
Anyone know how to increase the time out from 5 minutes to something longer to avoid failAbandonedQueries?

**Comment by forrestlmj** [comment] 2021-11-02 10:12
I set query.client.timeout to 20 minutes , still get the same error, has anyone solved the problem?
